// All 64 districts of Bangladesh
// Ordered: Dhaka first, then popular districts, then remaining alphabetical
export const BANGLADESH_DISTRICTS = [
  // First: Dhaka (Capital)
  'Dhaka',
  
  // Popular districts
  'Chittagong',
  'Rajshahi',
  'Rangpur',
  'Sylhet',
  'Khulna',
  'Barishal',
  "Cox's Bazar",
  
  // Remaining districts in alphabetical order
  'Bagerhat',
  'Bandarban',
  'Barguna',
  'Bhola',
  'Bogra',
  'Brahmanbaria',
  'Chandpur',
  'Chapai Nawabganj',
  'Chuadanga',
  'Cumilla',
  'Dinajpur',
  'Faridpur',
  'Feni',
  'Gaibandha',
  'Gazipur',
  'Gopalganj',
  'Habiganj',
  'Jamalpur',
  'Jashore',
  'Jhalokati',
  'Jhenaidah',
  'Joypurhat',
  'Khagrachari',
  'Kishoreganj',
  'Kurigram',
  'Kushtia',
  'Lakshmipur',
  'Lalmonirhat',
  'Madaripur',
  'Magura',
  'Manikganj',
  'Meherpur',
  'Moulvibazar',
  'Munshiganj',
  'Mymensingh',
  'Naogaon',
  'Narail',
  'Narayanganj',
  'Narsingdi',
  'Natore',
  'Netrokona',
  'Nilphamari',
  'Noakhali',
  'Pabna',
  'Panchagarh',
  'Patuakhali',
  'Pirojpur',
  'Rajbari',
  'Rangamati',
  'Satkhira',
  'Shariatpur',
  'Sherpur',
  'Sirajganj',
  'Sunamganj',
  'Tangail',
  'Thakurgaon',
] as const

// Type for district
export type District = typeof BANGLADESH_DISTRICTS[number]
